### ISSUE TITLE
Pedantic error

### ISSUE THREAD

**Issue by ahmadhasan2k8** [daviddoria/vtkOBJWriter#5]
When I put vtkObjWriter in my modules I get the following errors because I have -Wpedantic set as my CXX_FLAGS
```
vtkOBJWriter.h:39:43: error: extra ‘;’ [-Werror=pedantic]
   vtkTypeMacro(vtkOBJWriter, vtkAlgorithm);
```
```
vtkOBJWriter.cpp:50:34: error: extra ‘;’ [-Werror=pedantic]
 vtkStandardNewMacro(vtkOBJWriter);
```
If I remove the semi-colons, surprisingly it compiles and also runs.

**Comment by daviddoria** [comment]
Seems reasonable since the macro will just "copy/paste" the code into that position, which already has all of its own semicolons. I'd be happy to accept a pull request!

**Comment by ahmadhasan2k8** [comment]
Sure. I have created a pull request.
